$ErrorActionPreference="Stop"; Set-StrictMode -Version Latest
$Root=Split-Path -Parent $MyInvocation.MyCommand.Path; . (Join-Path $Root "PACKAGE_RUNTIME.ps1")
if($env:PALWAKF_ASSISTANT_DEFAULT_PRIVILEGES_LOCAL_HARDENING_LIVE_WRITE_APPROVED -ne "YES"){throw "EXPLICIT_LIVE_WRITE_APPROVAL_ENV_NOT_SET"}
$E=Join-Path $Root "evidence"; New-Item -ItemType Directory -Path $E -Force|Out-Null; $S=Get-Date -Format "yyyyMMdd_HHmmss"
$A=Join-Path $E ("DEFAULT_PRIVILEGES_LOCAL_HARDENING_APPLY_"+$S+".txt"); $V=Join-Path $E ("DEFAULT_PRIVILEGES_LOCAL_HARDENING_VERIFY_"+$S+".txt")
Invoke-PsqlEvidence -SqlFile (Join-Path $Root "sql\02_CONTROLLED_LIVE_APPLY.sql") -EvidenceFile $A
$AT=Get-Content -LiteralPath $A -Raw
foreach($M in @("ASSISTANT_DEFAULT_PRIVILEGES_LOCAL_HARDENING_APPLY_COMPLETE","DIRECT_CLIENT_SCHEMA_DEFAULT_GRANTS=0","COMMIT")){if(-not $AT.Contains($M)){throw "APPLY_MARKER_NOT_FOUND::$M"}}
Write-Output "DEFAULT_PRIVILEGES_LOCAL_HARDENING_APPLY=PASS"
Invoke-PsqlEvidence -SqlFile (Join-Path $Root "sql\03_POST_APPLY_READ_ONLY_VERIFY.sql") -EvidenceFile $V
$VT=Get-Content -LiteralPath $V -Raw
foreach($M in @("ASSISTANT_DEFAULT_PRIVILEGES_LOCAL_HARDENING_VERIFY_COMPLETE","DIRECT_CLIENT_SCHEMA_DEFAULT_GRANTS=0","SERVICE_ROLE_SCHEMA_DEFAULTS=PRESERVED","GLOBAL_PUBLIC_FUNCTION_EXECUTE=REMAINS_EFFECTIVE_SEPARATE_HOLD","EXISTING_TABLE_GRANT_ROWS=184","EXISTING_ROUTINE_PRIVILEGE_ROWS=108","KNOWLEDGE_DOCUMENTS=614","ACTIVATION_RUNS=1","STRICT_CHAT_CANDIDATES=0","ROLLBACK")){if(-not $VT.Contains($M)){throw "VERIFY_MARKER_NOT_FOUND::$M"}}
Write-Output "POST_APPLY_READ_ONLY_VERIFY=PASS"; Write-Output "APPLY_AND_VERIFY=PASS"
